# @package _global_
# This header make any parameters in these configs global.

defaults:
  - default
  - override /system: crisp/eval
  - overide /data.use_sequence: True

train: false
system:
  clip_ckpt: ${model_path}/${choices.data}${camus_labels:${data.labels}}-crisp-${seed}.ckpt
  num_samples: 50
  uncertainty_threshold: 0.3