# @package _global_
# This header make any parameters in these configs global.

work_dir: ${hydra:runtime.cwd}

defaults:
  - default
  - override /system: crisp/train

name: ${choices.data}${camus_labels:${data.labels}}-crisp-${seed}.ckpt
