hydra:
 searchpath:
   - pkg://vital.config

defaults:
  - vital_default # This references default config from vital.config.vital_default.yaml
  - trainer: default
  - system: uncertainty
  - data: camus
  - logger: comet/online
  - callbacks:
      - early_stopping
      - model_checkpoint
  - override system/module: enet

# Set comet project name and workspace
logger:
  project_name: crisp-miccai2022
  workspace: gungui02

seed: 55

trainer:
  max_epochs: 1000
  train: True
  test: True

callbacks:
  early_stopping:
    patience: 100
